version: '3.8'

services:
  geolocation:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/home/app/web

  db:
    image: postgis/postgis:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - db-volume:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  data-volume:
  db-volume:
